controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
task_monitor:
    path: /task-monitor
    controller: App\Controller\TaskMonitorController::index